pipelines:
  mypipe:
    group: mygroup
    materials:
      mygit:
        git: https://github.com/sandro-h/sonar-build-breaker.git
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: echo
                    arguments: ["hi"]